import jsPDF from "jspdf";
import type { SmartNote } from "./notes";

export function generatePDF(note: SmartNote): void {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 18;
  const contentW = pageW - margin * 2;
  let y = 0;

  const addPage = () => {
    doc.addPage();
    y = margin;
    // page header stripe
    doc.setFillColor(37, 99, 235);
    doc.rect(0, 0, pageW, 10, "F");
    doc.setFontSize(8);
    doc.setTextColor(255, 255, 255);
    doc.text("Phoenix AI — Smart Notes", margin, 7);
    doc.text(`Page ${doc.getNumberOfPages()}`, pageW - margin, 7, { align: "right" });
    doc.setTextColor(30, 30, 30);
    y = 18;
  };

  const checkY = (needed: number) => {
    if (y + needed > pageH - 20) addPage();
  };

  // ── Cover Header ──────────────────────────────────────────────────────────
  doc.setFillColor(37, 99, 235);
  doc.rect(0, 0, pageW, 42, "F");

  // Phoenix AI branding
  doc.setFontSize(11);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text("🎓 Phoenix AI", margin, 14);

  // Title
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  const titleLines = doc.splitTextToSize(note.title, contentW);
  doc.text(titleLines, margin, 26);

  // Meta info bar
  doc.setFillColor(17, 24, 39);
  doc.rect(0, 42, pageW, 12, "F");
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(156, 163, 175);
  const dateStr = new Date(note.createdAt).toLocaleDateString("en-IN", {
    weekday: "long", year: "numeric", month: "long", day: "numeric",
  });
  doc.text(`📅 ${dateStr}`, margin, 50);
  doc.text(`🤖 Agent: ${note.agentUsed}`, pageW / 2, 50);
  doc.text(`💬 ${note.messages.length} messages`, pageW - margin, 50, { align: "right" });

  y = 62;

  // ── Summary Section ───────────────────────────────────────────────────────
  doc.setFillColor(239, 246, 255);
  doc.roundedRect(margin - 4, y - 4, contentW + 8, 14, 3, 3, "F");
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(37, 99, 235);
  doc.text("📝 Study Session Notes", margin, y + 6);
  y += 18;

  // ── Messages ──────────────────────────────────────────────────────────────
  note.messages.forEach((msg) => {
    const isUser = msg.role === "user";
    const label = isUser ? "You" : (note.agentUsed === "orchestrator" ? "Phoenix AI" : note.agentUsed);
    const bgColor: [number, number, number] = isUser ? [219, 234, 254] : [240, 253, 244];
    const labelColor: [number, number, number] = isUser ? [37, 99, 235] : [22, 163, 74];
    const textColor: [number, number, number] = [30, 30, 30];

    // Wrap text
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...textColor);
    const lines: string[] = doc.splitTextToSize(msg.content, contentW - 8);
    const blockH = lines.length * 5.5 + 12;

    checkY(blockH + 6);

    // Message bubble background
    doc.setFillColor(...bgColor);
    doc.roundedRect(margin - 4, y - 2, contentW + 8, blockH, 3, 3, "F");

    // Label
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...labelColor);
    doc.text(label, margin, y + 5);

    // Timestamp
    if (msg.timestamp) {
      const ts = new Date(msg.timestamp).toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" });
      doc.setFontSize(7.5);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(150, 150, 150);
      doc.text(ts, margin + contentW, y + 5, { align: "right" });
    }

    // Message text
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...textColor);
    doc.text(lines, margin, y + 11);

    y += blockH + 6;
  });

  // ── Footer ────────────────────────────────────────────────────────────────
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFillColor(243, 244, 246);
    doc.rect(0, pageH - 12, pageW, 12, "F");
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(107, 114, 128);
    doc.text("Generated by Phoenix AI — Education For All", margin, pageH - 5);
    doc.text(`Page ${i} of ${totalPages}`, pageW - margin, pageH - 5, { align: "right" });
  }

  // Save
  const safeName = note.title.replace(/[^a-z0-9]/gi, "_").toLowerCase();
  doc.save(`phoenix_notes_${safeName}.pdf`);
}
